"""Report generation — Markdown, LaTeX, CSV, JSON, PDF (publication-ready)."""
from __future__ import annotations

import io
import json

import pandas as pd


def markdown_report(df: pd.DataFrame, title: str = "Benchmark Report") -> str:
    """Render a markdown report from a metrics DataFrame."""
    lines = [
        f"# {title}",
        "",
        f"*Generated by Cognitive Vision Lab v2.0 — {pd.Timestamp.now():%Y-%m-%d %H:%M}*",
        "",
        "## Summary",
        "",
    ]
    if df.empty:
        lines.append("_No models selected._")
        return "\n".join(lines)
    top_clean = df.sort_values("Clean %", ascending=False).iloc[0]
    lines += [
        f"- **Highest clean accuracy:** {top_clean['Model']} ({top_clean['Clean %']:.1f}%)",
        f"- **Models compared:** {len(df)}",
        "",
        "## Results",
        "",
        "| " + " | ".join(str(c) for c in df.columns) + " |",
        "|" + "|".join(["---"] * len(df.columns)) + "|",
    ]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(_fmt(v) for v in row.tolist()) + " |")
    lines += [
        "",
        "## Methods",
        "",
        "PGD-50, L∞, per-channel norm-space epsilon clamp (Finding-17 convention).",
        "d′ = Φ⁻¹(HR) − Φ⁻¹(FAR); εthresh = first ε where macro d′ < 1.0.",
    ]
    return "\n".join(lines)


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.2f}" if abs(v) < 1000 else f"{v:.3g}"
    return str(v)


def latex_table(df: pd.DataFrame) -> str:
    cols = df.columns.tolist()
    body = "\n".join(
        " & ".join(_latex_escape(_fmt(v)) for v in row.tolist()) + r" \\"
        for _, row in df.iterrows()
    )
    return (
        "\\begin{table}[h]\n\\centering\n\\begin{tabular}{"
        + ("l" + "c" * (len(cols) - 1)) + "}\n\\toprule\n"
        + " & ".join(_latex_escape(str(c)) for c in cols) + r" \\"
        + "\n\\midrule\n" + body + "\n\\bottomrule\n\\end{tabular}\n"
        + "\\caption{Model comparison.}\n\\end{table}"
    )


def _latex_escape(s: str) -> str:
    return s.replace("_", "\\_").replace("%", "\\%").replace("&", "\\&").replace("#", "\\#")


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode()


def to_json_bytes(df: pd.DataFrame) -> bytes:
    return json.dumps(df.to_dict(orient="records"), indent=2).encode()


def to_markdown_bytes(text: str) -> bytes:
    return text.encode()


def pdf_bytes(df: pd.DataFrame, title: str = "Benchmark Report") -> bytes:
    """Minimal publication-style PDF via matplotlib (no heavy LaTeX needed)."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig, ax = plt.subplots(figsize=(10, max(3, 0.5 * (len(df) + 2))))
        ax.axis("off")
        cols = df.columns.tolist()
        table = ax.table(cellText=df.round(2).astype(str).values, colLabels=cols,
                         loc="center", cellLoc="center")
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1, 1.4)
        ax.set_title(title, fontsize=14, pad=16)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)
    return buf.getvalue()
